import { Inter } from "next/font/google";
import { Abril_Fatface } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Abril = Abril_Fatface({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-Abril",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Abril.variable}`}>{children}</body>
    </html>
  );
}
